FROM flink:1.16.0

RUN wget -P /opt/flink/lib https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/1.16.0/flink-sql-connector-kafka-1.16.0.jar
RUN wget -P /opt/flink/lib/ https://github.com/knaufk/flink-faker/releases/download/v0.4.0/flink-faker-0.4.0.jar

