FROM flink:1.14.4

RUN wget -P /opt/flink/lib https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka_2.12/1.14.4/flink-sql-connector-kafka_2.12-1.14.4.jar
RUN wget -P /opt/flink/lib/ https://github.com/knaufk/flink-faker/releases/download/v0.4.0/flink-faker-0.4.0.jar

